from __future__ import annotations

import re
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile, ZipInfo

from lxml import etree


ROOT = Path(__file__).resolve().parent
TARGETS = [
    ROOT / "fase_planeacion_control_acceso_v2_corregida.docx",
    ROOT / "plan_adquisicion_equipos_y_costos_control_acceso_v2.docx",
]

W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
NS = {"w": W_NS}

# Correcciones seguras para la redaccion institucional y tecnica de ambos documentos.
REPLACEMENTS = {
    "administracion": "administración",
    "Administracion": "Administración",
    "planeacion": "planeación",
    "Planeacion": "Planeación",
    "conclusion": "conclusión",
    "Conclusion": "Conclusión",
    "bibliografia": "bibliografía",
    "Bibliografia": "Bibliografía",
    "descripcion": "descripción",
    "Descripcion": "Descripción",
    "delimitacion": "delimitación",
    "Delimitacion": "Delimitación",
    "justificacion": "justificación",
    "Justificacion": "Justificación",
    "informacion": "información",
    "Informacion": "Información",
    "situacion": "situación",
    "Situacion": "Situación",
    "version": "versión",
    "Version": "Versión",
    "aplicacion": "aplicación",
    "Aplicacion": "Aplicación",
    "integracion": "integración",
    "Integracion": "Integración",
    "gestion": "gestión",
    "Gestion": "Gestión",
    "sesion": "sesión",
    "Sesion": "Sesión",
    "programacion": "programación",
    "Programacion": "Programación",
    "autenticacion": "autenticación",
    "Autenticacion": "Autenticación",
    "autorizacion": "autorización",
    "Autorizacion": "Autorización",
    "validacion": "validación",
    "Validacion": "Validación",
    "migracion": "migración",
    "Migracion": "Migración",
    "operacion": "operación",
    "Operacion": "Operación",
    "revision": "revisión",
    "Revision": "Revisión",
    "asignacion": "asignación",
    "Asignacion": "Asignación",
    "capacitacion": "capacitación",
    "Capacitacion": "Capacitación",
    "evaluacion": "evaluación",
    "Evaluacion": "Evaluación",
    "condicion": "condición",
    "Condicion": "Condición",
    "conexion": "conexión",
    "Conexion": "Conexión",
    "institucion": "institución",
    "Institucion": "Institución",
    "proteccion": "protección",
    "Proteccion": "Protección",
    "recuperacion": "recuperación",
    "Recuperacion": "Recuperación",
    "verificacion": "verificación",
    "Verificacion": "Verificación",
    "planificacion": "planificación",
    "Planificacion": "Planificación",
    "implementacion": "implementación",
    "Implementacion": "Implementación",
    "adopcion": "adopción",
    "Adopcion": "Adopción",
    "restriccion": "restricción",
    "Restriccion": "Restricción",
    "expiracion": "expiración",
    "Expiracion": "Expiración",
    "paginacion": "paginación",
    "Paginacion": "Paginación",
    "rotacion": "rotación",
    "Rotacion": "Rotación",
    "relacion": "relación",
    "Relacion": "Relación",
    "organizacion": "organización",
    "Organizacion": "Organización",
    "analisis": "análisis",
    "Analisis": "Análisis",
    "codificacion": "codificación",
    "Codificacion": "Codificación",
    "correccion": "corrección",
    "Correccion": "Corrección",
    "tecnologia": "tecnología",
    "Tecnologia": "Tecnología",
    "tecnica": "técnica",
    "Tecnica": "Técnica",
    "tecnico": "técnico",
    "Tecnico": "Técnico",
    "tecnicos": "técnicos",
    "Tecnicos": "Técnicos",
    "tecnicamente": "técnicamente",
    "economica": "económica",
    "Economica": "Económica",
    "analitica": "analítica",
    "Analitica": "Analítica",
    "vehiculos": "vehículos",
    "Vehiculos": "Vehículos",
    "movil": "móvil",
    "Movil": "Móvil",
    "moviles": "móviles",
    "Moviles": "Móviles",
    "camara": "cámara",
    "Camara": "Cámara",
    "fotografias": "fotografías",
    "Fotografias": "Fotografías",
    "maximo": "máximo",
    "Maximo": "Máximo",
    "atomico": "atómico",
    "Atomico": "Atómico",
    "criticos": "críticos",
    "Criticos": "Críticos",
    "codigo": "código",
    "Codigo": "Código",
    "codigos": "códigos",
    "Codigos": "Códigos",
    "numero": "número",
    "Numero": "Número",
    "numeros": "números",
    "Numeros": "Números",
    "practica": "práctica",
    "Practica": "Práctica",
    "basica": "básica",
    "Basica": "Básica",
    "historica": "histórica",
    "Historica": "Histórica",
    "fisica": "física",
    "Fisica": "Física",
    "fisico": "físico",
    "Fisico": "Físico",
    "rapida": "rápida",
    "Rapida": "Rápida",
    "rapido": "rápido",
    "Rapido": "Rápido",
    "automatico": "automático",
    "Automatico": "Automático",
    "automaticos": "automáticos",
    "unico": "único",
    "Unico": "Único",
    "unicos": "únicos",
    "facil": "fácil",
    "Facil": "Fácil",
    "autonoma": "autónoma",
    "Autonoma": "Autónoma",
    "teorica": "teórica",
    "Teorica": "Teórica",
    "proposito": "propósito",
    "Proposito": "Propósito",
    "decision": "decisión",
    "Decision": "Decisión",
    "presentacion": "presentación",
    "Presentacion": "Presentación",
    "documentacion": "documentación",
    "Documentacion": "Documentación",
    "direccion": "dirección",
    "Direccion": "Dirección",
    "comunicacion": "comunicación",
    "Comunicacion": "Comunicación",
    "ano": "año",
    "Ano": "Año",
    "anos": "años",
    "dias": "días",
    "dia": "día",
    "tambien": "también",
    "Tambien": "También",
    "mas": "más",
    "Mas": "Más",
    "diseno": "diseño",
    "Diseno": "Diseño",
    "disenar": "diseñar",
    "Disenar": "Diseñar",
    "contrasenas": "contraseñas",
    "Politecnica": "Politécnica",
    "Cancun": "Cancún",
    "Mejia": "Mejía",
    "Guzman": "Guzmán",
    "Raul": "Raúl",
    "Angel": "Ángel",
    "Noe": "Noé",
    "Canche": "Canché",
    "Gongora": "Góngora",
    "auditoria": "auditoría",
    "Auditoria": "Auditoría",
    "reaccion": "reacción",
    "Reaccion": "Reacción",
    "informatica": "informática",
    "Informatica": "Informática",
    "solucion": "solución",
    "Solucion": "Solución",
    "dinamico": "dinámico",
    "Dinamico": "Dinámico",
    "dinamica": "dinámica",
    "Dinamica": "Dinámica",
    "atomicas": "atómicas",
    "Atomicas": "Atómicas",
    "friccion": "fricción",
    "Friccion": "Fricción",
    "separacion": "separación",
    "Separacion": "Separación",
    "aportacion": "aportación",
    "Aportacion": "Aportación",
    "adquisicion": "adquisición",
    "Adquisicion": "Adquisición",
    "prestamo": "préstamo",
    "Prestamo": "Préstamo",
    "devolucion": "devolución",
    "Devolucion": "Devolución",
    "impresion": "impresión",
    "Impresion": "Impresión",
    "ofimatica": "ofimática",
    "Ofimatica": "Ofimática",
    "configuracion": "configuración",
    "Configuracion": "Configuración",
    "reposicion": "reposición",
    "Reposicion": "Reposición",
    "sustitucion": "sustitución",
    "Sustitucion": "Sustitución",
    "autonomia": "autonomía",
    "Autonomia": "Autonomía",
    "academica": "académica",
    "Academica": "Académica",
    "academicas": "académicas",
    "Academicas": "Académicas",
    "historicos": "históricos",
    "Historicos": "Históricos",
    "minimo": "mínimo",
    "Minimo": "Mínimo",
    "intervencion": "intervención",
    "Intervencion": "Intervención",
    "unica": "única",
    "Unica": "Única",
    "aportara": "aportará",
    "mantendrian": "mantendrían",
    "postergarian": "postergarían",
    "agregara": "agregará",
    "debera": "deberá",
    "deberan": "deberán",
    "podra": "podrá",
    "requerira": "requerirá",
    "permitira": "permitirá",
    "lider": "líder",
    "Lider": "Líder",
    "indice": "índice",
    "Indice": "Índice",
    "seccion": "sección",
    "Seccion": "Sección",
    "pagina": "página",
    "Pagina": "Página",
    "reunion": "reunión",
    "Reunion": "Reunión",
    "asesoria": "asesoría",
    "Asesoria": "Asesoría",
    "retroalimentacion": "retroalimentación",
    "Retroalimentacion": "Retroalimentación",
    "duracion": "duración",
    "Duracion": "Duración",
    "precision": "precisión",
    "Precision": "Precisión",
    "cubriran": "cubrirán",
    "fisicas": "físicas",
    "Fisicas": "Físicas",
    "reduccion": "reducción",
    "Reduccion": "Reducción",
    "aplicara": "aplicará",
    "bitacora": "bitácora",
    "Bitacora": "Bitácora",
    "disponibilidad": "disponibilidad",
    "computo": "cómputo",
    "Computo": "Cómputo",
    "historica": "histórica",
    "Historica": "Histórica",
    "reportes": "reportes",
    "periodo": "período",
    "Periodo": "Período",
    "organica": "orgánica",
    "Organica": "Orgánica",
    "practico": "práctico",
    "Practico": "Práctico",
    "critico": "crítico",
    "Critico": "Crítico",
    "economico": "económico",
    "Economico": "Económico",
    "estandar": "estándar",
    "Estandar": "Estándar",
    "academico": "académico",
    "Academico": "Académico",
    "satisfaccion": "satisfacción",
    "Satisfaccion": "Satisfacción",
    "supervision": "supervisión",
    "Supervision": "Supervisión",
    "operara": "operará",
    "utilizara": "utilizará",
    "permitiran": "permitirán",
    "garantizara": "garantizará",
    "revisara": "revisará",
    "continuara": "continuará",
    "realizara": "realizará",
    "integrara": "integrará",
    "actualizara": "actualizará",
    "identificacion": "identificación",
    "Identificacion": "Identificación",
    "administrador": "administrador",
    "administradores": "administradores",
    "garantia": "garantía",
    "Garantia": "Garantía",
    "danio": "daño",
    "Danio": "Daño",
    "perdida": "pérdida",
    "Perdida": "Pérdida",
    "exposicion": "exposición",
    "Exposicion": "Exposición",
    "incorporacion": "incorporación",
    "Incorporacion": "Incorporación",
    "estimacion": "estimación",
    "Estimacion": "Estimación",
    "matricula": "matrícula",
    "Matricula": "Matrícula",
    "matriculas": "matrículas",
    "Matriculas": "Matrículas",
    "ampliacion": "ampliación",
    "Ampliacion": "Ampliación",
    "hibrido": "híbrido",
    "Hibrido": "Híbrido",
    "ejecucion": "ejecución",
    "Ejecucion": "Ejecución",
    "asesorias": "asesorías",
    "Asesorias": "Asesorías",
    "comparacion": "comparación",
    "Comparacion": "Comparación",
    "practicas": "prácticas",
    "Practicas": "Prácticas",
    "personalizacion": "personalización",
    "Personalizacion": "Personalización",
    "biometria": "biometría",
    "Biometria": "Biometría",
    "fisicos": "físicos",
    "Fisicos": "Físicos",
    "tecnologico": "tecnológico",
    "Tecnologico": "Tecnológico",
    "mitigacion": "mitigación",
    "Mitigacion": "Mitigación",
    "sincronizacion": "sincronización",
    "Sincronizacion": "Sincronización",
    "indices": "índices",
    "Indices": "Índices",
    "definicion": "definición",
    "Definicion": "Definición",
    "aceptacion": "aceptación",
    "Aceptacion": "Aceptación",
    "preparacion": "preparación",
    "Preparacion": "Preparación",
    "diagnostico": "diagnóstico",
    "Diagnostico": "Diagnóstico",
    "demostracion": "demostración",
    "Demostracion": "Demostración",
    "validaciones": "validaciones",
    "quien": "quién",
    "Quien": "Quién",
    "entro": "entró",
    "salio": "salió",
    "vehiculo": "vehículo",
    "Vehiculo": "Vehículo",
    "presento": "presentó",
    "realizo": "realizó",
    "permitio": "permitió",
    "tenia": "tenía",
    "pedia": "pedía",
    "tipica": "típica",
    "Tipica": "Típica",
    "dieciseis": "dieciséis",
    "Dieciseis": "Dieciséis",
    "bateria": "batería",
    "Bateria": "Batería",
    "construccion": "construcción",
    "Construccion": "Construcción",
    "cotizacion": "cotización",
    "Cotizacion": "Cotización",
    "cotizaciones": "cotizaciones",
    "maxima": "máxima",
    "Maxima": "Máxima",
    "basico": "básico",
    "Basico": "Básico",
    "electrica": "eléctrica",
    "Electrica": "Eléctrica",
    "termica": "térmica",
    "Termica": "Térmica",
    "restauracion": "restauración",
    "Restauracion": "Restauración",
    "fotografica": "fotográfica",
    "Fotografica": "Fotográfica",
    "critica": "crítica",
    "Critica": "Crítica",
    "POLITECNICA": "POLITÉCNICA",
    "ADMINISTRACION": "ADMINISTRACIÓN",
    "PLANEACION": "PLANEACIÓN",
    "CAMARA": "CÁMARA",
    "GONGORA": "GÓNGORA",
    "RAUL": "RAÚL",
    "NOE": "NOÉ",
    "ANGEL": "ÁNGEL",
    "CANCHE": "CANCHÉ",
    "MEJIA": "MEJÍA",
    "GUZMAN": "GUZMÁN",
    "CANCUN": "CANCÚN",
}

PATTERN = re.compile(r"\b(" + "|".join(sorted(map(re.escape, REPLACEMENTS), key=len, reverse=True)) + r")\b")


def normalize_text(text: str | None) -> str | None:
    if not text:
        return text
    return PATTERN.sub(lambda match: REPLACEMENTS[match.group(0)], text)


def normalize_docx(path: Path) -> None:
    temporary = path.with_suffix(".normalizing.docx")
    with ZipFile(path, "r") as source, ZipFile(temporary, "w") as output:
        for info in source.infolist():
            data = source.read(info.filename)
            if info.filename.startswith("word/") and info.filename.endswith(".xml"):
                root = etree.fromstring(data)
                changed = False
                for text_node in root.xpath(".//w:t", namespaces=NS):
                    value = normalize_text(text_node.text)
                    if value != text_node.text:
                        text_node.text = value
                        changed = True
                if changed:
                    data = etree.tostring(root, xml_declaration=True, encoding="UTF-8", standalone="yes")
            new_info = ZipInfo(info.filename, date_time=info.date_time)
            new_info.compress_type = info.compress_type or ZIP_DEFLATED
            new_info.comment = info.comment
            new_info.extra = info.extra
            new_info.internal_attr = info.internal_attr
            new_info.external_attr = info.external_attr
            new_info.create_system = info.create_system
            output.writestr(new_info, data)
    temporary.replace(path)


if __name__ == "__main__":
    for target in TARGETS:
        normalize_docx(target)
        print(target)
